### ISSUE TITLE
Create Vector Layer for farms

### ISSUE THREAD

**Issue by miafrank** [1904labs/geostack-farm-app#5]
Create Vector Layer for farms and add to map. 

Include the following in the `Vector Layer` `Source Vector` features: 

- Farm/Seller name 
- Farm/Seller email 
- Farm/Seller phone number
- Farm/Seller location  
- Farmer/Seller pick up location
- Farm/Seller price ranges
- Farm/Seller available products

[Here](https://demo.ol-kit.com/?view=38.971010,-89.826071,9.68,0.00) is an example of a Vector Layer on an ol-kit map and the [source](https://github.com/MonsantoCo/ol-kit/blob/6b218f865592cf3d6515ecf5e691443bec0f89ba/app/App.js) code.

**Comment by Swandog** [comment]
My fake farmer data does not have some of this data, do you want me to add it?

**Comment by miafrank** [comment]
@Swandog Yes please!
